import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from 'react'
import { ClerkProvider } from '@clerk/nextjs'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // Check if we're in a static build environment
  const isStaticBuild = process.env.NEXT_PHASE === 'phase-production-build';
  
  // If we're in a static build, don't use ClerkProvider
  if (isStaticBuild) {
    return (
      <html lang="en">
        <body>{children}</body>
      </html>
    );
  }
  
  return (
    <ClerkProvider>
      <html lang="en"
      data-theme="light"
       suppressHydrationWarning
      
      >
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
